spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  cloud:
    bus:
      enabled: false
logging:
  level:
    com.test.dao: debug
mybatis-plus:
  mapper-locations: /*.xml
